### Overpass API (OpenStreetMap)
### Query nodes and ways by OSM tags
### Docs: https://wiki.openstreetmap.org/wiki/Overpass_API

@baseUrl = https://overpass-api.de/api/interpreter

### Find fuel stations near Paris (approximate bbox)
POST {{baseUrl}}
Content-Type: application/x-www-form-urlencoded

data=[out:json][timeout:25];
(
  node["amenity"="fuel"](48.8,-2.4,48.9,-2.3);
  way["amenity"="fuel"](48.8,-2.4,48.9,-2.3);
);
out center qt 50;

### Find EV charging stations near London
POST {{baseUrl}}
Content-Type: application/x-www-form-urlencoded

data=[out:json][timeout:25];
(
  node["amenity"="charging_station"](51.45,-0.2,51.55,0.0);
  way["amenity"="charging_station"](51.45,-0.2,51.55,0.0);
);
out center qt 50;

### Find drinking water near Rome
POST {{baseUrl}}
Content-Type: application/x-www-form-urlencoded

data=[out:json][timeout:25];
(
  node["amenity"="drinking_water"](41.8,12.4,42.0,12.6);
);
out body qt 100;
